spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

  cassandra:
    keyspace-name: main
    schema-action: RECREATE_DROP_UNUSED
    request:
      timeout: 5s
    connection:
      connect-timeout: 5s
      init-query-timeout: 5s
    local-datacenter: datacenter1
    contact-points: localhost
    port: 9042

logging:
  level:
    org:
      springframework:
        security: DEBUG
#        /-- CAN SET TO TRACE --/