spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.48afd366d031475c
            client-secret: 0094e73785ec3f4ac3e04ad7b18c77a5cbc740d4


  data:
    cassandra:
      keyspace_name: main
      username: hJmlHgkwmLSrvIoOtuzfjNPq
      password: ZP6.ROCk1dh6tJU1ZbZic1L4ghWuplI_wAoSrp38GLv9ZftNBkIBO0gmrKy5lNFcB.siH0aYSUXh0sD,-AUHo2XqGGWtKYdZQAhexhttUG1rGouGK-qqvnn6UhxZbwn4
      schema-action: RECREATE_DROP_UNUSED
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

astra.db:
  id: 01cc1736-65c8-4a92-9cad-c2dcf1adec68-1
  region: asia-south1
  keyspace: main
  application.token: AstraCS:hJmlHgkwmLSrvIoOtuzfjNPq:c8bd228eadb0011e4646891e49d74bf9d43a2233de53edfb6c01d1f9bdb713f8

datastax.astra:
  secure-connect-bundle: secure-connect.zip